import Foundation

// Jellyfin's trickplay: preview frames for scrubbing, generated by the server
// (10.9 and later, per library) as JPEG sheets. Each sheet is a grid of
// TileWidth x TileHeight frames of Width x Height pixels, one frame every
// Interval milliseconds. The item's `Trickplay` field is the manifest:
// media source id -> frame width -> the numbers below. A library with
// trickplay off has no manifest, and the scrubber shows time and chapter only.

public struct TrickplayInfo: Codable, Sendable, Equatable {
    public var width: Int?
    public var height: Int?
    public var tileWidth: Int?
    public var tileHeight: Int?
    public var thumbnailCount: Int?
    public var interval: Int?

    public init(width: Int?, height: Int?, tileWidth: Int?, tileHeight: Int?, thumbnailCount: Int?, interval: Int?) {
        self.width = width; self.height = height
        self.tileWidth = tileWidth; self.tileHeight = tileHeight
        self.thumbnailCount = thumbnailCount; self.interval = interval
    }
}

/// One preview frame: which sheet to fetch and where in it the frame sits, in
/// the sheet's pixels.
public struct TrickplayFrame: Sendable, Equatable {
    public var sheet: Int
    public var x: Int
    public var y: Int
    public var width: Int
    public var height: Int
}

/// A usable manifest entry, with the frame width the sheet URL is keyed by.
public struct Trickplay: Sendable, Equatable {
    public var frameWidth: Int
    public var info: TrickplayInfo

    public init(frameWidth: Int, info: TrickplayInfo) {
        self.frameWidth = frameWidth
        self.info = info
    }

    /// Picks the entry for `mediaSourceId` (its key went through the JSON case
    /// rule, so it is compared without case, and a manifest with one source is
    /// that source), at the smallest width of at least `preferredWidth`, else
    /// the largest there is. Nil when nothing in it can be drawn.
    public static func pick(_ manifest: [String: [String: TrickplayInfo]]?, mediaSourceId: String?,
                            preferredWidth: Int = 320) -> Trickplay? {
        guard let manifest, !manifest.isEmpty else { return nil }
        let widths = manifest.first { $0.key.caseInsensitiveCompare(mediaSourceId ?? "") == .orderedSame }?.value
            ?? (manifest.count == 1 ? manifest.first?.value : nil)
        let usable = (widths ?? [:]).compactMap { key, info -> Trickplay? in
            guard let w = Int(key), Trickplay(frameWidth: w, info: info).isUsable else { return nil }
            return Trickplay(frameWidth: w, info: info)
        }.sorted { $0.frameWidth < $1.frameWidth }
        return usable.first { $0.frameWidth >= preferredWidth } ?? usable.last
    }

    var isUsable: Bool {
        [info.width, info.height, info.tileWidth, info.tileHeight, info.thumbnailCount, info.interval]
            .allSatisfy { ($0 ?? 0) > 0 }
    }

    /// The frame for a position in the film (not the player's clock, which a
    /// transcode starts partway in). Past the end is the last frame.
    public func frame(atSeconds seconds: Double) -> TrickplayFrame? {
        guard isUsable, let w = info.width, let h = info.height, let tw = info.tileWidth, let th = info.tileHeight,
              let count = info.thumbnailCount, let interval = info.interval, seconds.isFinite else { return nil }
        let index = min(max(0, Int(seconds * 1000) / interval), count - 1)
        let perSheet = tw * th
        let within = index % perSheet
        return TrickplayFrame(sheet: index / perSheet, x: (within % tw) * w, y: (within / tw) * h, width: w, height: h)
    }
}

/// The item fields the player asks for once per video.
public struct VideoDetails: Sendable, Equatable {
    public var chapters: [Chapter]
    public var trickplay: [String: [String: TrickplayInfo]]?
}

public extension JellyfinClient {
    /// Chapters and the trickplay manifest in one request. A failed request is
    /// a video without either, never an error.
    func videoDetails(for item: JfItem) async -> VideoDetails {
        struct Response: Decodable { var chapters: [JfChapter]?; var trickplay: [String: [String: TrickplayInfo]]? }
        guard let r: Response = try? await get("/Users/\(currentConfig.userId)/Items/\(item.id)",
                                               params: ["fields": "Chapters,Trickplay"]) else {
            return VideoDetails(chapters: [], trickplay: nil)
        }
        return VideoDetails(chapters: Chapters.list(r.chapters, runTimeTicks: item.runTimeTicks), trickplay: r.trickplay)
    }

    /// One trickplay sheet, as JPEG data. Through the API session, since the
    /// route wants the token (unlike artwork).
    func trickplaySheet(itemId: String, mediaSourceId: String?, frameWidth: Int, sheet: Int) async throws -> Data {
        try await getData("/Videos/\(itemId)/Trickplay/\(frameWidth)/\(sheet).jpg", params: ["mediaSourceId": mediaSourceId])
    }
}
