const sharp = require('sharp')
const path = require('path')
const fs = require('fs')
const { execSync } = require('child_process')

const OUT = path.join(__dirname, '../assets')

// Largest icon produced. Nothing here scales past it, so a raster source at
// this size loses nothing to a vector one - see resolveSource().
const MAX_SIZE = 1024

// Source candidates, best first. Named source.* rather than icon.* on purpose:
// icon.png/.ico/.icns are what this script WRITES, so a source sharing one of
// those names would be overwritten by its own output halfway through the run.
const CANDIDATES = ['source.svg', 'source.png']
const GENERATED = path.join(OUT, 'icon.png')

// Where the artwork's subject sits, as a fraction of its width and height. The
// installer images are small crops, not the whole square, and they are centered
// here so they land on the waterfall rather than empty sky.
// ponytail: tuned by eye for the current source.png; move it if the art changes.
const INSTALLER_FOCUS = { x: 0.66, y: 0.26 }

function q(p) { return `"${p}"` }

/** NSIS only takes 24-bit BMP for its installer images, and sharp cannot write
 *  BMP, so this is the minimal encoder: a 54 byte header, then bottom-up BGR
 *  rows padded to 4 bytes. `raw` is sharp's output with 3 channels. */
function writeBmp(file, { data, info }) {
  const { width: w, height: h } = info
  const row = Math.ceil((w * 3) / 4) * 4
  const buf = Buffer.alloc(54 + row * h)
  buf.write('BM', 0)
  buf.writeUInt32LE(buf.length, 2)
  buf.writeUInt32LE(54, 10)       // pixel data offset
  buf.writeUInt32LE(40, 14)       // BITMAPINFOHEADER size
  buf.writeInt32LE(w, 18)
  buf.writeInt32LE(h, 22)         // positive = bottom-up
  buf.writeUInt16LE(1, 26)        // planes
  buf.writeUInt16LE(24, 28)       // bits per pixel
  buf.writeUInt32LE(row * h, 34)
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const s = (y * w + x) * 3
      const d = 54 + (h - 1 - y) * row + x * 3
      buf[d] = data[s + 2]; buf[d + 1] = data[s + 1]; buf[d + 2] = data[s]
    }
  }
  fs.writeFileSync(file, buf)
}

/** A width x height crop of the artwork scaled to `scale` px square, centered
 *  on INSTALLER_FOCUS and clamped so it never runs off the edge. */
async function installerImage(src, file, scale, width, height) {
  const left = Math.round(Math.min(scale - width,  Math.max(0, scale * INSTALLER_FOCUS.x - width / 2)))
  const top  = Math.round(Math.min(scale - height, Math.max(0, scale * INSTALLER_FOCUS.y - height / 2)))
  const raw = await sharp(src).resize(scale, scale).extract({ left, top, width, height })
    .flatten({ background: '#111113' }).raw().toBuffer({ resolveWithObject: true })
  writeBmp(path.join(OUT, file), raw)
  console.log(`  ${file}`)
}

/** Which file to generate from: an explicit CLI argument, else the first
 *  candidate that exists. Vector wins when both are present, since it is the
 *  better master, but it says so out loud - silently generating from a stale
 *  source.svg after someone dropped in new artwork as source.png is exactly
 *  the kind of thing that ships the wrong logo. */
function resolveSource() {
  const arg = process.argv[2]
  if (arg) {
    const p = path.resolve(arg)
    if (!fs.existsSync(p)) throw new Error(`No such file: ${arg}`)
    return p
  }
  const found = CANDIDATES.map(n => path.join(OUT, n)).filter(p => fs.existsSync(p))
  if (!found.length) {
    throw new Error(
      `No icon source found. Put one of these in assets/:\n` +
      CANDIDATES.map(n => `  ${n}`).join('\n') +
      `\nOr pass a path: npm run icons -- path/to/artwork.png`)
  }
  if (found.length > 1) {
    console.log(`Note: ${found.map(p => path.basename(p)).join(' and ')} both exist.`)
    console.log(`      Using ${path.basename(found[0])}. To use the other:`)
    console.log(`      npm run icons -- assets/${path.basename(found[1])}\n`)
  }
  return found[0]
}

/** A raster source below MAX_SIZE would be upscaled, which looks soft at
 *  exactly the sizes people notice (the dock and the installer). Vector is
 *  exempt: sharp renders it at whatever size is asked for. */
async function checkSize(src) {
  if (path.extname(src).toLowerCase() === '.svg') return
  const { width, height } = await sharp(src).metadata()
  if (width < MAX_SIZE || height < MAX_SIZE) {
    throw new Error(
      `${path.basename(src)} is ${width}x${height}, and icons are generated up ` +
      `to ${MAX_SIZE}x${MAX_SIZE}.\nUpscaling would look soft. Ask for a ` +
      `${MAX_SIZE}x${MAX_SIZE} export or an SVG.`)
  }
  if (width !== height) {
    console.log(`Warning: ${path.basename(src)} is ${width}x${height}, not square.`)
    console.log(`         It will be squashed to fit. Crop it first if that matters.\n`)
  }
}

async function run() {
  const SRC = resolveSource()
  if (path.resolve(SRC) === GENERATED) {
    throw new Error(`assets/icon.png is generated by this script, so it cannot also be the source.\nRename it to assets/source.png.`)
  }
  await checkSize(SRC)
  console.log(`Generating icons from ${path.basename(SRC)}...`)

  const sizes = [16, 32, 48, 64, 128, 256, 512, MAX_SIZE]
  for (const s of sizes) {
    await sharp(SRC).resize(s, s).png().toFile(path.join(OUT, `icon-${s}.png`))
  }

  // icon.png (Linux)
  fs.copyFileSync(path.join(OUT, `icon-${MAX_SIZE}.png`), path.join(OUT, 'icon.png'))
  console.log('  icon.png')

  // icon.icns (macOS) via iconutil
  if (process.platform === 'darwin') {
    const icnsDir = path.join(OUT, 'icon.iconset')
    fs.mkdirSync(icnsDir, { recursive: true })
    const icnsMap = {
      16:   'icon_16x16',
      32:   'icon_16x16@2x',
      64:   'icon_32x32@2x',
      128:  'icon_128x128',
      256:  'icon_128x128@2x',
      512:  'icon_256x256@2x',
      [MAX_SIZE]: 'icon_512x512@2x',
    }
    for (const [s, name] of Object.entries(icnsMap)) {
      fs.copyFileSync(path.join(OUT, `icon-${s}.png`), path.join(icnsDir, `${name}.png`))
    }
    execSync(`iconutil -c icns ${q(icnsDir)} -o ${q(path.join(OUT, 'icon.icns'))}`)
    fs.rmSync(icnsDir, { recursive: true })
    console.log('  icon.icns')
  } else {
    console.log('  icon.icns - skipped (run on macOS to generate)')
  }

  // icon.ico (Windows) - embed multiple sizes using sharp + manual ICO construction
  // Simple approach: use the 256px png as a single-image ICO
  // (electron-builder accepts a png renamed .ico for basic builds)
  const png256 = fs.readFileSync(path.join(OUT, 'icon-256.png'))
  const icoPath = path.join(OUT, 'icon.ico')

  // Build a minimal valid ICO with one 256x256 entry
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0)   // reserved
  header.writeUInt16LE(1, 2)   // type: ICO
  header.writeUInt16LE(1, 4)   // count: 1 image

  const entry = Buffer.alloc(16)
  entry.writeUInt8(0, 0)       // width  (0 = 256)
  entry.writeUInt8(0, 1)       // height (0 = 256)
  entry.writeUInt8(0, 2)       // color count
  entry.writeUInt8(0, 3)       // reserved
  entry.writeUInt16LE(1, 4)    // color planes
  entry.writeUInt16LE(32, 6)   // bits per pixel
  entry.writeUInt32LE(png256.length, 8)    // size of image data
  entry.writeUInt32LE(6 + 16, 12)          // offset of image data

  fs.writeFileSync(icoPath, Buffer.concat([header, entry, png256]))
  console.log('  icon.ico')

  // Clean up intermediate pngs
  for (const s of sizes) {
    const f = path.join(OUT, `icon-${s}.png`)
    if (s !== MAX_SIZE) fs.unlinkSync(f)
  }
  // rename 1024 to icon.png already done above, remove the numbered one
  try { fs.unlinkSync(path.join(OUT, `icon-${MAX_SIZE}.png`)) } catch {}

  // Windows installer art. Sizes are fixed by NSIS: the welcome and finish page
  // sidebar is 164x314, the header on every other page is 150x57.
  await installerImage(SRC, 'installer-sidebar.bmp', 314, 164, 314)
  await installerImage(SRC, 'installer-header.bmp', 300, 150, 57)

  console.log('\nDone. Icons written to assets/')
}

run().catch(err => { console.error(err.message || err); process.exit(1) })
